config/routes.rb
Coinplanner::Application.routes.draw do

  devise_for :admins
  get "pages/login"

  resources :tickets

  resources :events

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :time, :street_address, :city, :state, :zip, :description, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def login
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:attendee_id, :event_id, :tier_id, :order_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="event-title">
      <%= f.label :title %><br>
    </div>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <div class="date-label">
      <%= f.label :date %><br>
    </div>
    <%= f.text_field :date %>
  </div>
  <div class="field" >
    <div class="time-select-box">
      <%= f.label :time %><br>
      <div class="time-select">
        <%= f.time_select :time %>
      </div>
    </div>
   </div>
  <div class="field">
    <div class="street-address">
      <%= f.label :street_address %><br>
    </div>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
      <div class="description-label">
        <%= f.label :description %><br>
      </div>
        <div class="description-field">
          <%= f.text_area :description %>
        </div>


  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Save'%>
  </div>
<% end %>

app/views/events/edit.html.erb
    <div class="outsideborder">

      <div class="content">


        <div class="event-details">
          <div class="event-title"><h1>Edit Details</h1></div>
          <%= render 'form' %>

        </div>


    </div>
<!--<%= link_to 'Show', @event %> |
# <%= link_to 'Back', events_path %> -->

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Time</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.street_address %></td>
        <td><%= event.city %></td>
        <td><%= event.state %></td>
        <td><%= event.zip %></td>
        <td><%= event.description %></td>
        <td><%= event.user_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<div class="outsideborder">
  <div class="content">
    <%= render 'form' %>
  </div>
</div>


<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="outsideborder">
  <div class="content">
    <div class="event-details">
      <div class="event-title">
        <h1><%= @event.title %></h1>
      </div>
      <div class="date-label">
        <h3>Date:</h3>
      </div>
      <div class="date">
        <h3><%= @event.date.strftime("%A, %b %d") %> at <%= @event.time.strftime("%l:%m %p") %></h3>
      </div>
      <div class="place-label">
        <h3>Place:</h3>
      </div>
      <div class="street-address">
        <h3><%= @event.street_address %><h3>
      </div>
      <div class="city-zip">
        <h3><%= @event.city %>, <%= @event.state %> <%= @event.zip %></h3>
      </div>
      <div class="description">
         <%= simple_format @event.description %>

      </div>
      <a href="https://coinbase.com/checkouts/f8e9180f240eaee258ebf636fa1768bf" target="_blank"><button>Buy a Ticket!</button></a>
    </div>


  </div>

</div>





<!-- <p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coinplanner</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar">
      <h1 class='navbar-text-left'>Coinplanner</h1><!-- left sidebar -->

      <h1 class="navbar-text-right">☰</h1>
  </nav>

<%= yield %>

</body>
</html>

app/views/pages/login.html.erb
    <div class="outsideborder">

      <div class="content">

        <input type="email" placeholder="Coinbase Email"></input>

        <input type="password" placeholder="Coinbase Password"></input>

        <a href="http://localhost:3000/events/1"><button type="submit" class="button-mobile">Log in with Coinbase</button></a>

          <div>
            <div class="getcoinbase">

              Don't have a Coinbase account?

            </div>

             <div class="getcoinbase">
              Get Coinbase.
            </div>

        </div>
      </div>

    </div>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attendee_id %><br>
    <%= f.number_field :attendee_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :tier_id %><br>
    <%= f.text_field :tier_id %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.datetime_select :order_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Attendee</th>
      <th>Event</th>
      <th>Tier</th>
      <th>Order date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.attendee_id %></td>
        <td><%= ticket.event_id %></td>
        <td><%= ticket.tier_id %></td>
        <td><%= ticket.order_date %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attendee:</strong>
  <%= @ticket.attendee_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event_id %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @ticket.tier_id %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @ticket.order_date %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>